### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by cool-RR** [msbrogli/rpudb#4]
I tried rpudb for the first time, tried to connect to a Hello World example, got this: 

    [root@vxms-simbuild83 foo]# python bar.py
    pudb is running on 0.0.0.0:6899
    Mainloop
    Traceback (most recent call last):
      File "bar.py", line 4, in <module>
        rpudb.set_trace(addr='0.0.0.0', port=6899)
      File "/usr/lib/python2.6/site-packages/rpudb/__init__.py", line 101, in set_trace
        (pid, stdout, stdin) = run_telnet_server(addr, port)
      File "/usr/lib/python2.6/site-packages/rpudb/__init__.py", line 82, in run_telnet_server
        assert(cmd[3] == 0)
    AssertionError
    /usr/lib/python2.6/site-packages/pudb/__init__.py:202: UserWarning: A non-default handler for signal 2 is already installed (<function signal_handler at 0x7fce480bbc80>). Skipping pudb interrupt support.
      % (interrupt_signal, old_handler))

**Comment by msbrogli** [comment]
Hi @cool-RR. It seems that the IAC packet is different from expected. I'm thinking that you first run `python bar.py` and then you tried to connect using a telnet. Am I right? Something like `telnet localhost 6899`?

What is your operating system?
Could you print the value of the `cmd` variable after line 80?
Can you show the source code of `bar.py`?

**Comment by cool-RR** [comment]
Hi Marcelo,

Thanks for the quick reply, and sorry, I lost interest in the bug. (I found
a way to use pudb over SSH.) I'll answer the easy questions in case it's
useful for you but I don't want to investigate more than that.

"I'm thinking that you first run python bar.py and then you tried to
connect using a telnet. Am I right? Something like telnet localhost 6899?"
Yes you're right.

OS is Centos 6 dot something.

bar.py was just some simple hello world program with "import rpudb;
rpudb.set_trace(addr='0.0.0.0', port=6899)" at the start.

**Comment by msbrogli** [comment]
@cool-RR No problem. It happens. I could not replicate the bug, unfortunately. Anyway, how do you use pudb over SSH? Maybe it is also useful for me. :)

**Comment by cool-RR** [comment]
I'm developing a Python tool that lets my team members run tests on a remote machine. The tests use pytest, so I installed pytest-pudb and I'm launching them with the `--pudb` flag. On the user's machine I use subprocess, and ssh with the `-t` switch to the machine. Then I can see the nice PuDB interface on the local machine.
